dependencies:
- name: catalog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: checkout
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: inventory
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: user
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
